<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>MusicaAprender.DatabaseReliabilityVerifier</AssemblyName>
        <RootNamespace>MusicaAprender.DatabaseReliabilityVerifier</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\BuildingBlocks\Infrastructure\MusicaAprender.BuildingBlocks.Infrastructure.csproj" />
    </ItemGroup>
</Project>
