<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MusicaAprender.BuildingBlocks.Infrastructure</AssemblyName>
    <RootNamespace>MusicaAprender.BuildingBlocks.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Minio" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\MusicaAprender.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Domain\MusicaAprender.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\Contracts\MusicaAprender.BuildingBlocks.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="..\..\..\database\postgresql\ef-model\cross-schema-foreign-keys.json"
      LogicalName="MusicaAprender.BuildingBlocks.Infrastructure.Database.Modeling.CrossSchemaForeignKeys.json" />
  </ItemGroup>
</Project>
