<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>MusicaAprender.DatabaseAccessVerifier</AssemblyName>
    <RootNamespace>MusicaAprender.DatabaseAccessVerifier</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
