$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
Set-Location $Root

function Get-DotEnvValue([string]$Name, [string]$DefaultValue) {
    if (-not (Test-Path ".env")) {
        return $DefaultValue
    }

    $match = Get-Content ".env" |
        Where-Object { $_ -match "^\s*$([regex]::Escape($Name))\s*=" } |
        Select-Object -Last 1

    if ($null -eq $match) {
        return $DefaultValue
    }

    return (($match -split "=", 2)[1]).Trim()
}

function Assert-LastExitCode([string]$Step) {
    if ($LASTEXITCODE -ne 0) {
        throw "$Step fallo con codigo de salida $LASTEXITCODE."
    }
}

function Add-AutoGeneratedHeader([string]$Directory) {
    if (-not (Test-Path $Directory)) {
        throw "No existe el directorio generado '$Directory'."
    }

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)

    Get-ChildItem -Path $Directory -Recurse -Filter *.cs -File |
        ForEach-Object {
            $content = [System.IO.File]::ReadAllText($_.FullName)

            if ($content.StartsWith("// <auto-generated />`n#nullable enable", [System.StringComparison]::Ordinal)) {
                return
            }

            if ($content.StartsWith("// <auto-generated />", [System.StringComparison]::Ordinal)) {
                $content = $content.Substring("// <auto-generated />".Length).TrimStart("`r", "`n")
            }

            [System.IO.File]::WriteAllText(
                $_.FullName,
                "// <auto-generated />`n#nullable enable`n" + $content,
                $utf8NoBom)
        }
}

$dbName = Get-DotEnvValue "POSTGRES_DB" "musica_aprender"
$dbPort = Get-DotEnvValue "POSTGRES_PORT" "5432"
$passwordPath = Join-Path $Root "secrets\local\postgres_migrator_password"

if (-not (Test-Path $passwordPath)) {
    throw "Falta secrets/local/postgres_migrator_password."
}

$password = [System.IO.File]::ReadAllText($passwordPath).Trim()

if ($password -notmatch '^[0-9a-f]{48,}$') {
    throw "El secreto postgres_migrator_password no tiene el formato local esperado."
}

if ($dbName -notmatch '^[A-Za-z_][A-Za-z0-9_]{0,62}$' -or
    $dbPort -notmatch '^\d{1,5}$') {
    throw "Configuracion PostgreSQL local no cumple el formato seguro esperado."
}

$connectionString = "Host=127.0.0.1;Port=$dbPort;Database=$dbName;Username=jp_login_migrator;Password=$password;Include Error Detail=false;Pooling=false;Timeout=15"
$scaffoldProject = "tools/DatabaseMigrator/MusicaAprender.DatabaseMigrator.csproj"

dotnet tool restore
Assert-LastExitCode "dotnet tool restore"

$targets = @(
    @{
        Schema = "identity"
        Context = "IdentityDbContext"
        ContextDir = "../../src/Modules/Identity/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Identity/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Identity.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Identity.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Identity\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "security"
        Context = "SecurityDbContext"
        ContextDir = "../../src/Modules/Security/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Security/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Security.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Security.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Security\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "catalog"
        Context = "CatalogDbContext"
        ContextDir = "../../src/Modules/Catalog/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Catalog/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Catalog.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Catalog.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Catalog\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "content"
        Context = "ContentDbContext"
        ContextDir = "../../src/Modules/Content/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Content/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Content.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Content.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Content\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "learning"
        Context = "LearningDbContext"
        ContextDir = "../../src/Modules/Learning/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Learning/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Learning.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Learning.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Learning\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "progress"
        Context = "ProgressDbContext"
        ContextDir = "../../src/Modules/Progress/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Progress/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Progress.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Progress.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Progress\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "editorial"
        Context = "EditorialDbContext"
        ContextDir = "../../src/Modules/Editorial/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Editorial/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Editorial.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Editorial.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Editorial\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "configuration"
        Context = "ConfigurationDbContext"
        ContextDir = "../../src/Modules/Configuration/Infrastructure/Persistence/Generated"
        EntityDir = "../../src/Modules/Configuration/Infrastructure/Persistence/Generated/Entities"
        Namespace = "MusicaAprender.Modules.Configuration.Infrastructure.Persistence.Entities"
        ContextNamespace = "MusicaAprender.Modules.Configuration.Infrastructure.Persistence"
        LocalGenerated = "src\Modules\Configuration\Infrastructure\Persistence\Generated"
    },
    @{
        Schema = "ops"
        Context = "OpsDbContext"
        ContextDir = "../../src/BuildingBlocks/Infrastructure/Database/Ops/Generated"
        EntityDir = "../../src/BuildingBlocks/Infrastructure/Database/Ops/Generated/Entities"
        Namespace = "MusicaAprender.BuildingBlocks.Infrastructure.Database.Ops.Entities"
        ContextNamespace = "MusicaAprender.BuildingBlocks.Infrastructure.Database.Ops"
        LocalGenerated = "src\BuildingBlocks\Infrastructure\Database\Ops\Generated"
    }
)

foreach ($target in $targets) {
    $localPath = Join-Path $Root $target.LocalGenerated

    if (Test-Path $localPath) {
        Remove-Item -Recurse -Force $localPath
    }

    Write-Host "Scaffolding EF Core: $($target.Schema) -> $($target.Context)..."

    dotnet ef dbcontext scaffold `
        $connectionString `
        Npgsql.EntityFrameworkCore.PostgreSQL `
        --project $scaffoldProject `
        --startup-project $scaffoldProject `
        --schema $target.Schema `
        --context $target.Context `
        --context-dir $target.ContextDir `
        --output-dir $target.EntityDir `
        --namespace $target.Namespace `
        --context-namespace $target.ContextNamespace `
        --no-onconfiguring `
        --no-pluralize `
        --force

    Assert-LastExitCode "Scaffold del esquema $($target.Schema)"

    Add-AutoGeneratedHeader $localPath
}

Write-Host "OK: codigo reverse-engineered marcado como auto-generado para analizadores."

Write-Host "OK: nueve DbContext propietarios regenerados desde PostgreSQL 18."
