export type AppArea = 'public' | 'student' | 'editorial' | 'administration';

export type RouteAccess =
  'public' | 'one-time-token' | 'public-or-student' | 'student' | 'capability';

export type CapabilityMode = 'any' | 'all';

export type AppRoute = {
  id: `UI-MVP-${string}`;
  area: AppArea;
  title: string;
  path: string;
  canonicalPath?: string;
  access: RouteAccess;
  accessLabel: string;
  queryKey?: string;
  requiredCapabilities?: readonly string[];
  capabilityMode?: CapabilityMode;
};

export const routeManifest: readonly AppRoute[] = [
  {
    id: 'UI-MVP-001',
    area: 'public',
    title: 'Inicio',
    path: '/',
    access: 'public',
    accessLabel: 'Público',
  },
  {
    id: 'UI-MVP-003',
    area: 'public',
    title: 'Resultados de búsqueda',
    path: '/canciones',
    canonicalPath: '/canciones?consulta=',
    queryKey: 'consulta',
    access: 'public',
    accessLabel: 'Público',
  },
  {
    id: 'UI-MVP-002',
    area: 'public',
    title: 'Catálogo de canciones',
    path: '/canciones',
    access: 'public',
    accessLabel: 'Público',
  },
  {
    id: 'UI-MVP-004',
    area: 'public',
    title: 'Ficha pública de canción',
    path: '/canciones/{slug}',
    access: 'public',
    accessLabel: 'Público',
  },
  {
    id: 'UI-MVP-005',
    area: 'public',
    title: 'Registro',
    path: '/registro',
    access: 'public',
    accessLabel: 'Público',
  },
  {
    id: 'UI-MVP-006',
    area: 'public',
    title: 'Verificación',
    path: '/verificar-cuenta',
    access: 'one-time-token',
    accessLabel: 'Token de un uso validado por servidor',
  },
  {
    id: 'UI-MVP-007',
    area: 'public',
    title: 'Acceso',
    path: '/acceso',
    access: 'public',
    accessLabel: 'Público',
  },
  {
    id: 'UI-MVP-008',
    area: 'student',
    title: 'Preferencias',
    path: '/preferencias',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-009',
    area: 'student',
    title: 'Reproductor educativo',
    path: '/aprender/{slug}',
    access: 'public-or-student',
    accessLabel: 'Público/estudiante',
  },
  {
    id: 'UI-MVP-010',
    area: 'student',
    title: 'Análisis contextual',
    path: '/aprender/{slug}/analisis/{token}',
    access: 'public-or-student',
    accessLabel: 'Público/estudiante',
  },
  {
    id: 'UI-MVP-011',
    area: 'student',
    title: 'Inicio de estudio',
    path: '/estudiar/{slug}',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-012',
    area: 'student',
    title: 'Ejercicio contextual',
    path: '/estudiar/{slug}/ejercicio/{id}',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-013',
    area: 'student',
    title: 'Resultado y retroalimentación',
    path: '/estudiar/{slug}/resultado/{id}',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-014',
    area: 'student',
    title: 'Resumen de progreso',
    path: '/progreso',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-015',
    area: 'student',
    title: 'Progreso de canción',
    path: '/progreso/canciones/{slug}',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-016',
    area: 'student',
    title: 'Reanudar',
    path: '/reanudar',
    access: 'student',
    accessLabel: 'Estudiante',
  },
  {
    id: 'UI-MVP-017',
    area: 'editorial',
    title: 'Bandeja editorial',
    path: '/editorial',
    access: 'capability',
    accessLabel: 'Interno',
    requiredCapabilities: [
      'EDITORIAL.DRAFT',
      'EDITORIAL.REVIEW',
      'EDITORIAL.PUBLISH',
      'EDITORIAL.CORRECT',
    ],
    capabilityMode: 'any',
  },
  {
    id: 'UI-MVP-018',
    area: 'editorial',
    title: 'Nueva canción',
    path: '/editorial/canciones/nueva',
    access: 'capability',
    accessLabel: 'Editor',
    requiredCapabilities: ['EDITORIAL.DRAFT'],
  },
  {
    id: 'UI-MVP-019',
    area: 'editorial',
    title: 'Expediente de canción',
    path: '/editorial/canciones/{id}',
    access: 'capability',
    accessLabel: 'Interno por alcance',
    requiredCapabilities: [
      'EDITORIAL.DRAFT',
      'EDITORIAL.REVIEW',
      'EDITORIAL.PUBLISH',
      'EDITORIAL.CORRECT',
    ],
    capabilityMode: 'any',
  },
  {
    id: 'UI-MVP-020',
    area: 'editorial',
    title: 'Derechos y procedencia',
    path: '/editorial/canciones/{id}/derechos',
    access: 'capability',
    accessLabel: 'Editor/revisor',
    requiredCapabilities: ['EDITORIAL.DRAFT', 'EDITORIAL.REVIEW'],
    capabilityMode: 'any',
  },
  {
    id: 'UI-MVP-021',
    area: 'editorial',
    title: 'Editor de letra',
    path: '/editorial/canciones/{id}/letra',
    access: 'capability',
    accessLabel: 'Editor',
    requiredCapabilities: ['EDITORIAL.DRAFT'],
  },
  {
    id: 'UI-MVP-022',
    area: 'editorial',
    title: 'Sincronización',
    path: '/editorial/canciones/{id}/sincronizacion',
    access: 'capability',
    accessLabel: 'Editor',
    requiredCapabilities: ['EDITORIAL.DRAFT'],
  },
  {
    id: 'UI-MVP-023',
    area: 'editorial',
    title: 'Traducción',
    path: '/editorial/canciones/{id}/traduccion',
    access: 'capability',
    accessLabel: 'Traductor/revisor',
    requiredCapabilities: ['EDITORIAL.DRAFT', 'EDITORIAL.REVIEW'],
    capabilityMode: 'any',
  },
  {
    id: 'UI-MVP-024',
    area: 'editorial',
    title: 'Análisis lingüístico',
    path: '/editorial/canciones/{id}/analisis',
    access: 'capability',
    accessLabel: 'Editor/revisor',
    requiredCapabilities: ['EDITORIAL.DRAFT', 'EDITORIAL.REVIEW'],
    capabilityMode: 'any',
  },
  {
    id: 'UI-MVP-025',
    area: 'editorial',
    title: 'Banco de ejercicios',
    path: '/editorial/canciones/{id}/ejercicios',
    access: 'capability',
    accessLabel: 'Editor',
    requiredCapabilities: ['EDITORIAL.DRAFT'],
  },
  {
    id: 'UI-MVP-026',
    area: 'editorial',
    title: 'Paquete y sometimiento',
    path: '/editorial/paquetes/{id}',
    access: 'capability',
    accessLabel: 'Editor/revisor',
    requiredCapabilities: ['EDITORIAL.SUBMIT', 'EDITORIAL.REVIEW'],
    capabilityMode: 'any',
  },
  {
    id: 'UI-MVP-027',
    area: 'administration',
    title: 'Revisión y publicación',
    path: '/administracion/publicaciones/{id}',
    access: 'capability',
    accessLabel: 'Administrador',
    requiredCapabilities: ['EDITORIAL.PUBLISH'],
  },
  {
    id: 'UI-MVP-028',
    area: 'administration',
    title: 'Corrección o reversión',
    path: '/administracion/correcciones/{id}',
    access: 'capability',
    accessLabel: 'Administrador',
    requiredCapabilities: ['EDITORIAL.CORRECT'],
  },
  {
    id: 'UI-MVP-029',
    area: 'administration',
    title: 'Roles y permisos',
    path: '/administracion/roles',
    access: 'capability',
    accessLabel: 'Administrador',
    requiredCapabilities: ['SECURITY.MANAGE_ROLES'],
  },
  {
    id: 'UI-MVP-030',
    area: 'administration',
    title: 'Catálogos y parámetros',
    path: '/administracion/configuracion',
    access: 'capability',
    accessLabel: 'Administrador',
    requiredCapabilities: ['CONFIG.MANAGE'],
  },
  {
    id: 'UI-MVP-031',
    area: 'administration',
    title: 'Auditoría',
    path: '/administracion/auditoria',
    access: 'capability',
    accessLabel: 'Administrador',
    requiredCapabilities: ['SECURITY.READ_AUDIT'],
  },
  {
    id: 'UI-MVP-032',
    area: 'administration',
    title: 'Detalle de auditoría',
    path: '/administracion/auditoria/{evento}',
    access: 'capability',
    accessLabel: 'Administrador',
    requiredCapabilities: ['SECURITY.READ_AUDIT'],
  },
] as const;
